package entity;
// Generated 12/03/2020 04:57:17 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {

    // comentando ...
     private long id;
     private String nombre;
     private String email;

    public Usuario() {
    }

	
    public Usuario(long id) {
        this.id = id;
    }
    public Usuario(long id, String nombre, String email) {
       this.id = id;
       this.nombre = nombre;
       this.email = email;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


